asdfas

diff --git a/.github/workflows/build-package-win-x64.yml b/.github/workflows/build-package-win-x64.yml
--- a/.github/workflows/build-package-win-x64.yml
+++ b/.github/workflows/build-package-win-x64.yml
@@ -40,108 +40,113 @@ jobs:
       # initialize and fetch submodules with a shallow clone of 10 commits
       - name: Initialize and Update Submodules (Shallow)
         run: |
+          ls
           git submodule init
           git submodule update --recursive --depth 10
+          echo "Submodule initialization and update completed."
+          cd ./extensions/pearai-submodule
+          echo "Submodule directory changed to: $(pwd)"
+          git status
 
-      # Setup Python environment
-      - uses: actions/setup-python@v5
-        with:
-          python-version: "3.x"
-      # Setup Node.js environment
-      - uses: actions/setup-node@v4
-        with:
-          node-version-file: .nvmrc
+      # # Setup Python environment
+      # - uses: actions/setup-python@v5
+      #   with:
+      #     python-version: "3.x"
+      # # Setup Node.js environment
+      # - uses: actions/setup-node@v4
+      #   with:
+      #     node-version-file: .nvmrc
 
-      - name: Cache node modules
-        id: cache-node-modules
-        uses: actions/cache@v4
-        with:
-          path: '**/node_modules'
-          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
-          restore-keys: |
-            ${{ runner.os }}-node-
-
-      - name: Cache Yarn dependencies
-        uses: actions/cache@v4
-        with:
-          path: '**/node_modules'
-          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
-          restore-keys: |
-            ${{ runner.os }}-yarn-
-
-      - name: Setup Environment
-        run: |
-          .\scripts\pearai\setup-environment.ps1
-
-      # # Step 2: Set Build Path
-      # - name: Set Build Path
-      #   id: set-path
-      #   run: |
-      #     $username = [Environment]::UserName
-      #     $buildOutput = "C:\Users\$username\Desktop\vscode-win32-x64"
-      #     echo "build_path=$buildOutput" >> $env:GITHUB_OUTPUT
-
-      # # Step 3: Cache the build output
-      # # sdf
-      # - name: Cache Build Output
-      #   id: cache-restore
+      # - name: Cache node modules
+      #   id: cache-node-modules
       #   uses: actions/cache@v4
       #   with:
-      #     path: ${{ steps.set-path.outputs.build_path }}
-      #     key: vscode-win-x64-build
+      #     path: '**/node_modules'
+      #     key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
       #     restore-keys: |
-      #       vscode-win-x64-build
-      #     # key: vscode-win-x64-${{ github.sha }}
-      #     # restore-keys: |
-      #     #   vscode-win-x64-${{ github.sha }}
+      #       ${{ runner.os }}-node-
 
-      # $buildCacheHit = ${{ steps.cache-restore.outputs.cache-hit }}
-      # Step 5: Create a dummy folder and a temporary text file (if cache miss)
-      - name: Create Dummy Folder for Testing
-        run: |
-          $pearappCommitHash = '${{ inputs.pearapp-commit-hash }}'
-          $submoduleCommitHash = '${{ inputs.submodule-commit-hash }}'
-          $customPearappVersion = '${{ inputs.custom-pearapp-version }}'
-          $forceBuild = [System.Convert]::ToBoolean('${{ inputs.force-build }}')
-          Write-Host "pearappCommitHash: $pearappCommitHash"
-          Write-Host "submoduleCommitHash: $submoduleCommitHash"
-          Write-Host "customPearappVersion: $customPearappVersion"
-          Write-Host "forceBuild: $forceBuild"
+      # - name: Cache Yarn dependencies
+      #   uses: actions/cache@v4
+      #   with:
+      #     path: '**/node_modules'
+      #     key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
+      #     restore-keys: |
+      #       ${{ runner.os }}-yarn-
 
-          .\.github\workflows\testenv.ps1 `
-            -IS_GITHUB_ACTION $true `
-            -Input_PearappCommitHash $pearappCommitHash `
-            -Input_SubmoduleCommitHash $submoduleCommitHash `
-            -Input_CustomPearappVersion $customPearappVersion `
-            -Input_ForceBuild $forceBuild
+      # - name: Setup Environment
+      #   run: |
+      #     .\scripts\pearai\setup-environment.ps1
 
-      # Step 6: Verify Build Output and Set Output Variable
-      - name: Verify Build Output
-        id: verify-output
-        run: |
-          $username = [Environment]::UserName  # Get the current user's name
-          $buildOutput = "C:\Users\$username\Desktop\vscode-win32-x64"
-          if (-Not (Test-Path $buildOutput)) {
-            Write-Error "Build output not found at $buildOutput"
-            exit 1  # Exit with an error to stop the job
-          } else {
-            Write-Host "Build output found at $buildOutput"
-            echo "build_path=$buildOutput" >> $env:GITHUB_OUTPUT  # Set the output variable
-          }
+      # # # Step 2: Set Build Path
+      # # - name: Set Build Path
+      # #   id: set-path
+      # #   run: |
+      # #     $username = [Environment]::UserName
+      # #     $buildOutput = "C:\Users\$username\Desktop\vscode-win32-x64"
+      # #     echo "build_path=$buildOutput" >> $env:GITHUB_OUTPUT
 
-      # Step 7: Upload the Build Output (Zipped)
-      - name: Upload Build Output
-        uses: actions/upload-artifact@v4
-        with:
-          name: vscode-win32-x64
-          path: ${{ steps.verify-output.outputs.build_path }}
+      # # # Step 3: Cache the build output
+      # # # sdf
+      # # - name: Cache Build Output
+      # #   id: cache-restore
+      # #   uses: actions/cache@v4
+      # #   with:
+      # #     path: ${{ steps.set-path.outputs.build_path }}
+      # #     key: vscode-win-x64-build
+      # #     restore-keys: |
+      # #       vscode-win-x64-build
+      # #     # key: vscode-win-x64-${{ github.sha }}
+      # #     # restore-keys: |
+      # #     #   vscode-win-x64-${{ github.sha }}
 
-      # Optional: Debug step to verify file
-      - name: Debug - Check File Existence
-        run: |
-          $filepath = "${{ steps.verify-output.outputs.build_path }}\temp.txt"
-          if (Test-Path $filepath) {
-            Write-Host "File exists at: $filepath"
-          } else {
-            Write-Host "File not found at: $filepath"
-          }
+      # # $buildCacheHit = ${{ steps.cache-restore.outputs.cache-hit }}
+      # # Step 5: Create a dummy folder and a temporary text file (if cache miss)
+      # - name: Create Dummy Folder for Testing
+      #   run: |
+      #     $pearappCommitHash = '${{ inputs.pearapp-commit-hash }}'
+      #     $submoduleCommitHash = '${{ inputs.submodule-commit-hash }}'
+      #     $customPearappVersion = '${{ inputs.custom-pearapp-version }}'
+      #     $forceBuild = [System.Convert]::ToBoolean('${{ inputs.force-build }}')
+      #     Write-Host "pearappCommitHash: $pearappCommitHash"
+      #     Write-Host "submoduleCommitHash: $submoduleCommitHash"
+      #     Write-Host "customPearappVersion: $customPearappVersion"
+      #     Write-Host "forceBuild: $forceBuild"
+
+      #     .\.github\workflows\testenv.ps1 `
+      #       -IS_GITHUB_ACTION $true `
+      #       -Input_PearappCommitHash $pearappCommitHash `
+      #       -Input_SubmoduleCommitHash $submoduleCommitHash `
+      #       -Input_CustomPearappVersion $customPearappVersion `
+      #       -Input_ForceBuild $forceBuild
+
+      # # Step 6: Verify Build Output and Set Output Variable
+      # - name: Verify Build Output
+      #   id: verify-output
+      #   run: |
+      #     $username = [Environment]::UserName  # Get the current user's name
+      #     $buildOutput = "C:\Users\$username\Desktop\vscode-win32-x64"
+      #     if (-Not (Test-Path $buildOutput)) {
+      #       Write-Error "Build output not found at $buildOutput"
+      #       exit 1  # Exit with an error to stop the job
+      #     } else {
+      #       Write-Host "Build output found at $buildOutput"
+      #       echo "build_path=$buildOutput" >> $env:GITHUB_OUTPUT  # Set the output variable
+      #     }
+
+      # # Step 7: Upload the Build Output (Zipped)
+      # - name: Upload Build Output
+      #   uses: actions/upload-artifact@v4
+      #   with:
+      #     name: vscode-win32-x64
+      #     path: ${{ steps.verify-output.outputs.build_path }}
+
+      # # Optional: Debug step to verify file
+      # - name: Debug - Check File Existence
+      #   run: |
+      #     $filepath = "${{ steps.verify-output.outputs.build_path }}\temp.txt"
+      #     if (Test-Path $filepath) {
+      #       Write-Host "File exists at: $filepath"
+      #     } else {
+      #       Write-Host "File not found at: $filepath"
+      #     }
